name = "boltyyyy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
send_metrics = false

type = "worker"

[build]
command = "npm run build"  # یا دستور مناسب برای پروژه شما
cwd = "."
