name = "bolty"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

# اضافه کردن نقطه ورودی
main = "src/index.js"  # به مسیر فایل ورودی خود اشاره کنید
